root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/local/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", ".aws-sam", ".git"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "LAMBDA_RUNTIME_API=localhost:9001 AWS_SAM_LOCAL=true ./tmp/main"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "toml", "env"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
